name: (ci/cd workflow) setup git

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  setup-git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Set output
        id: set-output
        run: echo "setup-complete=true" >> $GITHUB_ENV

  feature-create-pr:
    runs-on: ubuntu-latest
    needs: setup-git

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Create Pull Request
        if: ${{ needs.setup-git.outputs.setup-complete == 'true' }}
        # if: ${{ github.event.workflow_run.conclusion == 'success' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated PR for new changes
          branch: ${{ github.head_ref }}
          base: develop
          title: Automated Pull Request from ${{ github.head_ref }}
          body: This pull request has been created automatically by GitHub Actions.
          delete-branch: false
          branch-suffix: timestamp