name: Criar Release

on:
  push:
    branches:
      - homolog

jobs:
  criar-branch-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout da branch homolog
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determinar a próxima versão da release
        id: next_version
        run: |
          # Lista as branches remotas que seguem o padrão "release/v*"
          branches=$(git ls-remote --heads origin "release/v*" | awk -F'release/v' '{print $2}' | sort -n)
          echo "Branches existentes: $branches"
          if [ -z "$branches" ]; then
            next=1
          else
            # Obtém o maior número
            max=$(echo "$branches" | tail -n1)
            next=$((max + 1))
          fi
          echo "Próxima versão: $next"
          echo "version=$next" >> $GITHUB_OUTPUT

      - name: Criar e enviar a nova branch release
        run: |
          RELEASE_BRANCH="release/v${{ steps.next_version.outputs.version }}"
          echo "Criando branch: $RELEASE_BRANCH"
          git checkout -b "$RELEASE_BRANCH"
          git push origin "$RELEASE_BRANCH"
