name: Auto Create Pull Request

on:
  push:
    branches:
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Base da PR: pode ser "develop" ou "homolog" dependendo do fluxo
          base: develop
          # Usa a branch atual como head
          branch: ${{ github.ref_name }}
          title: "PR automático: Merge de ${{ github.ref_name }} para develop"
          body: |
            Esse Pull Request foi criado automaticamente.
            Favor revisar as alterações e proceder com o merge se estiver tudo correto.
