name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Deploy para produção
        run: |
          # Comando para realizar o deploy, por exemplo:
          # npm run deploy
          echo "Realizando deploy para produção..."