name: Code Review

on:
  pull_request:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Executar análise de código
        run: |
          # Comando para executar análise de código, por exemplo:
          # npm run lint
          echo "Executando análise de código..."