name: (create-release) Cria Branch Release

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  setup-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          echo "Configurando Git..."
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          echo "Configuração do Git concluída."

      - name: Instalar git-flow
        run: |
          sudo apt-get update
          sudo apt-get install -y git-flow

      - name: Inicializar git-flow
        run: |
          git flow init -d

  create-release:
    runs-on: ubuntu-latest
    needs: setup-git
    steps:
      - name: Cache das tags do Git
        uses: actions/cache@v3
        with:
          path: |
            ~/.git-refs
          key: ${{ runner.os }}-git-${{ hashFiles('**/refs/tags') }}
          restore-keys: |
            ${{ runner.os }}-git-

      - name: Verifica se a branch foi criada a partir de develop
        run: |
          echo "Verificando se a branch foi criada a partir de develop..."
          BASE_BRANCH=$(git merge-base HEAD origin/develop)
          if [ "$BASE_BRANCH" != "$(git rev-parse origin/develop)" ]; then
            echo "Branches de release devem ser criadas a partir de develop."
            exit 1
          else
            echo "Branch criada corretamente a partir de develop."
          fi

      - name: Cria branch release
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          if [ -z "$latest_tag" ]; then
            new_version="v1.0.0"
          else
            new_version=$(echo $latest_tag | awk -F. -v OFS=. '{$NF++;print}')
          fi
          git flow release start $new_version
          git flow release finish $new_version
          git push origin --all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-pr:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Cria Pull Request
        if: ${{ steps.set_version.outputs.new_version != '' }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Incrementando versão de release'
          branch: 'release/${{ steps.set_version.outputs.new_version }}'
          base: 'main'
          title: 'release/${{ steps.set_version.outputs.new_version }}'
          body: |
            Este pull request inclui as seguintes alterações:
            - Incremento de versão para release