name: (create-release) Cria Branch Release

on:
  push:
    branches:
      - 'develop'
      - 'feature/*'
  pull_request:
    branches:
      - 'release/*'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write


jobs:
  setup-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          echo "Configurando Git..."
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          echo "Configuração do Git concluída."

#      - name: (git fetch) Busca todas as branches
#        run: git fetch --all

  create-release:
    runs-on: ubuntu-latest
    needs: setup-git
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache das tags do Git
        uses: actions/cache@v3
        with:
          path: |
            ~/.git-refs
          key: ${{ runner.os }}-git-${{ hashFiles('**/refs/tags') }}
          restore-keys: |
            ${{ runner.os }}-git-

      - name: Verifica se a branch foi criada a partir de develop ou feature/*
        run: |
          echo "Verificando se a branch foi criada a partir de develop ou feature/*..."
          BASE_BRANCH=$(git merge-base HEAD origin/develop)
          if [ "$BASE_BRANCH" != "$(git rev-parse origin/develop)" ] && [[ ! "$(git rev-parse --abbrev-ref HEAD)" =~ ^feature/ ]]; then
            echo "Branches de release devem ser criadas a partir de develop ou feature/*."
            exit 1
          else
            echo "Branch criada corretamente a partir de develop ou feature/*."
          fi

      - name: Cria branch release
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null)
          if [ -z "$latest_tag" ]; then
            new_version="v1.0.0"
          else
            new_version=$(echo $latest_tag | awk -F. -v OFS=. '{$NF++;print}')
          fi
          git checkout -b release/$new_version
          git push origin release/$new_version
        env:
          OIS_GITHUB_TOKEN: ${{ secrets.OIS_GITHUB_TOKEN }}

  create-pr:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Cria Pull Request
        if: ${{ steps.set_version.outputs.new_version != '' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.OIS_GITHUB_TOKEN }}
          commit-message: 'Incrementando versão de release'
          branch: 'release/${{ steps.set_version.outputs.new_version }}'
          base: 'main'
          title: 'release/${{ steps.set_version.outputs.new_version }}'
          body: |
            Este pull request inclui as seguintes alterações:
            - Incremento de versão para release

      - name: Exibir link do Pull Request
        run: |
          echo "Link do Pull Request: ${{ steps.create-pull-request.outputs.pull-request-url }}"