name: (feature-check) Verifica Origem da Branch de Feature

on:
  pull_request:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  setup-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Git
        run: |
          echo "Configurando Git..."
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          echo "Configuração do Git concluída."

      - name: Verificar se estamos no diretório correto do repositório
        run: |
          if [ ! -d ".git" ]; then
            echo "Diretório .git não encontrado. Verifique se você está no diretório correto do repositório."
            exit 1
          fi

  feature-check:
    runs-on: ubuntu-latest
    needs: setup-git
    steps:
      - name: Verifica origem da branch de feature
        run: |
          echo "Verificando origem da branch de feature..."
          git fetch --all
          git checkout develop || git checkout -b develop origin/develop
          DEVELOP_HEAD=$(git rev-parse origin/develop)
          LOCAL_DEVELOP_HEAD=$(git rev-parse develop)
          if [ "${{ github.event.pull_request.base.ref }}" != "develop" ] && [ "${{ github.event.pull_request.base.ref }}" != "$DEVELOP_HEAD" ] && [ "${{ github.event.pull_request.base.ref }}" != "$LOCAL_DEVELOP_HEAD" ]; then
            echo "Branches de feature devem ser criadas a partir de develop ou origin/develop."
            exit 1
          else
            echo "Branch de feature criada corretamente a partir de develop ou origin/develop."
          fi

  create-pr:
    runs-on: ubuntu-latest
    needs: [setup-git, feature-check]
    steps:
      - name: Obter título do commit mais recente
        id: get_commit_title
        run: echo "commit_title=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Cria Pull Request
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ env.commit_title }}
          branch: ${{ github.ref }}
          base: 'develop'
          title: 'Atualizações na feature branch'
          body: |
            Este pull request inclui as seguintes alterações:
            - Atualizações na feature branch