name: (setup-git) Passos Compartilhados

on:
  workflow_dispatch:

jobs:
  setup-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          echo "Configurando Git..."
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          echo "Configuração do Git concluída."
